[versions]
agp         = "8.5.0"
kotlin      = "2.0.0"
composeBom  = "2024.09.00"
lifecycleViewmodel = "2.8.3"
savedstate = "1.2.1"
startup     = "1.1.1"
coroutines  = "1.8.1"

[libraries]
compose-bom                 = { group = "androidx.compose",           name = "compose-bom",                version.ref = "composeBom" }
compose-ui                  = { group = "androidx.compose.ui",        name = "ui"                                                     }
compose-foundation          = { group = "androidx.compose.foundation",name = "foundation"                                             }
compose-material3           = { group = "androidx.compose.material3", name = "material3"                                              }
compose-material-icons-core = { group = "androidx.compose.material",  name = "material-icons-core"                                    }
compose-ui-tooling          = { group = "androidx.compose.ui",        name = "ui-tooling"                                             }
compose-ui-test             = { group = "androidx.compose.ui",        name = "ui-test-junit4"                                         }
compose-ui-test-manifest    = { group = "androidx.compose.ui",        name = "ui-test-manifest"                                       }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycleViewmodel" }
savedstate = { module = "androidx.savedstate:savedstate", version.ref = "savedstate" }
startup-runtime             = { group = "androidx.startup",           name = "startup-runtime",            version.ref = "startup"    }
coroutines-android          = { group = "org.jetbrains.kotlinx",      name = "kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test             = { group = "org.jetbrains.kotlinx",      name = "kotlinx-coroutines-test",    version.ref = "coroutines" }
junit                       = { group = "junit",                      name = "junit",                      version     = "4.13.2"     }
activity-compose            = { group = "androidx.activity",          name = "activity-compose",           version     = "1.9.0"      }

[plugins]
android-application = { id = "com.android.application",             version.ref = "agp"    }
android-library     = { id = "com.android.library",                 version.ref = "agp"    }
kotlin-android      = { id = "org.jetbrains.kotlin.android",        version.ref = "kotlin" }
compose-compiler    = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
maven-publish       = { id = "maven-publish" }
signing             = { id = "signing"        }
nmcp                = { id = "com.gradleup.nmcp", version = "0.0.9" }
